config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get '/create1' => 'sessions#create1'
  
  # get '/userslogin' => 'sessions#create'
  # post '/sessions/create' => '/sessions/create'

  get 'sessions/obtain_page'
  get 'sessions/obtainsuccess'
  get 'sessions/obtainerror1'

  post  'sessions/obtain'
  # post '/sessions/obtain' => '/sessions/obtain'

  get 'users/new'
  get 'users/registererror0'
  get 'users/registererror1'
  get 'users/registererror2'
  get '' => 'users#guide'


  # post  'users/create'
  post '/users/create' => 'users#create'

  get  'users/index'

  resources :wzxes
  get '/find' => 'wzxes#find'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/models/wzx.rb
class Wzx < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def new
 end
 
 def create1
  
  name =params[:name]
  password_confirm = params[:password_confirm]
  user = User.find_by(name: name )
  

  if (user.password_confirm == password_confirm)

   render json: {login_success:'yes'}
  else
   render json: {login_success:'no'}
  end
 end
 def  obtain_page	
 end
 def obtain 	
   user = User.find_by(name: user_params[:name])
   keykey = user_params[:key]
  if (user.key == keykey) 
     
    # redirect_to '/sessions/obtainsuccess'
     
    render json: {密码:user.password_confirm }
  elsif (user.name)
     render html: "<h1><strong>您的取密钥匙不正确</strong></h1>".html_safe
   # render json: {obtain_success:'no'}
  
  end
 end
 
 private
  def user_params
   params.require(:session).permit(:name, :password, :key, :password_confirm)
  end
end

app/controllers/users_controller.rb
 class UsersController < ApplicationController
 def new
  @user = User.new
 end

 def create 
  if (user_params[:name] == ''  || user_params[:password] == '' || user_params[:password_confirm] == '' || user_params[:key] == '')
    render html: "<h1><strong>您输入的信息不完全</strong></h1>".html_safe
    
  elsif (user_params[:password] != user_params[:password_confirm]) 
  render html: "<h1><strong>两次输入的密码不相同</strong></h1>".html_safe
 elsif 
  user = User.find_by(name: user_params[:name])
   # render json: {register:'Alread_exits_name'}
   render html: "<h1><strong>该用户名已经存在</strong></h1>".html_safe
  
 elsif     
   @user = User.create(user_params)
   @user.save
   
   # render json: {register_success:'yes'}
  
  end
end

def index
  @users = User.all
  end 
def guide
  
end
 private
  def user_params
   params.require(:user).permit(:name, :password, :password_confirm,:key)
  end
end

app/controllers/wzxes_controller.rb
class WzxesController < ApplicationController
  before_action :set_wzx, only: [:show, :edit, :update, :destroy]

  # GET /wzxes
  # GET /wzxes.json
  def find
  x = params[:x]
  y = params[:y]
  # distance =params[:distance]
  #{distance}
  data = Wzx.where("pt<->point'(#{x},#{y})'<5").order("pt<->point'(#{x},#{y})'").first
    # data1 =(id: data_id)
  render json:data
   
end
  def index
    @wzxes = Wzx.all
  end

  # GET /wzxes/1
  # GET /wzxes/1.json
  def show
  end

  # GET /wzxes/new
  def new
    @wzx = Wzx.new
  end

  # GET /wzxes/1/edit
  def edit
  end

  # POST /wzxes
  # POST /wzxes.json
  def create
    @wzx = Wzx.new(wzx_params)

    respond_to do |format|
      if @wzx.save
        format.html { redirect_to @wzx, notice: 'Wzx was successfully created.' }
        format.json { render :show, status: :created, location: @wzx }
      else
        format.html { render :new }
        format.json { render json: @wzx.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wzxes/1
  # PATCH/PUT /wzxes/1.json
  def update
    respond_to do |format|
      if @wzx.update(wzx_params)
        format.html { redirect_to @wzx, notice: 'Wzx was successfully updated.' }
        format.json { render :show, status: :ok, location: @wzx }
      else
        format.html { render :edit }
        format.json { render json: @wzx.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wzxes/1
  # DELETE /wzxes/1.json
  def destroy
    @wzx.destroy
    respond_to do |format|
      format.html { redirect_to wzxes_url, notice: 'Wzx was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wzx
      @wzx = Wzx.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wzx_params
      params.require(:wzx).permit(:name, :information, :food, :tuijian)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wzxes_helper.rb
module WzxesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test4</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
    
<HTML>
<HEAD>
<TITLE>注册成功</TITLE>
<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<style type="text/css">
<!--
body {
    background:url(../img/login_bg_0.jpg) #f8f6e9;
}
.mycenter{
    margin-top: 100px;
    margin-left: auto;
    margin-right: auto;
    height: 350px;
    width:500px;
    padding: 5%;
    padding-left: 5%;
    padding-right: 5%;
}
.mycenter mysign{
    width: 440px;
}
.mycenter input,checkbox,button{
    margin-top:2%;
    margin-left: 10%;
    margin-right: 10%;
}
.mycheckbox{
    margin-top:10px;
    margin-left: 40px;
    margin-bottom: 10px;
    height: 10px;
}-->
</style>
</HEAD>
<body>
        
            <div class="mycenter">
            <div class="mysign">
                <div class="col-xs-9 text-center text-info">
                    <h2>注册成功</h2>
                </div>
                
       </div>
       </div>
    </body>

</HTML>

app/views/users/guide.html.erb
<html>
<head>
<title>户外助手使用说明</title>
</head>
<body>
<h1>户外助手使用说明</h1>
<%= image_tag("1.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("2.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("3.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("4.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("5.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("6.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("7.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("8.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("9.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("10.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("11.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("12.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("13.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("14.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("15.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("16.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("17.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("18.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("19.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("20.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("21.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("22.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("23.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("24.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("25.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("26.jpg", width:"100%" , height:"280px") %><br><br>
<%= image_tag("27.jpg", width:"100%" , height:"280px") %><br><br>

</body>
</html>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>password_degist</th>
      <th>password_confirm</th>
      <th>key</th>
      <th>beiwanglu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% for user in @users %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.password_confirm %></td>
        <td><%= user.key %></td>
        <td><%= user.user_beiwanglu%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<HTML>
<HEAD>
<TITLE>注册</TITLE>
<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<style type="text/css">
<!--
body {
    background:url(../img/login_bg_0.jpg) #f8f6e9;
}
.mycenter{
    margin-top: 100px;
    margin-left: auto;
    margin-right: auto;
    height: 350px;
    width:500px;
    padding: 5%;
    padding-left: 5%;
    padding-right: 5%;
}
.mycenter mysign{
    width: 440px;
}
.mycenter input,checkbox,button{
    margin-top:2%;
    margin-left: 10%;
    margin-right: 10%;
}
.mycheckbox{
    margin-top:10px;
    margin-left: 40px;
    margin-bottom: 10px;
    height: 10px;
}-->
</style>
</HEAD>
<body>
        <%= form_for @user, url: :users_create do |f| %>
            <div class="mycenter">
            <div class="mysign">
                <div class="col-xs-12 col-sm-9 text-center text-info">
                    <h2>用户注册</h2>
                </div>
                <div class="col-xs-10"></div>
                <div class="col-xs-10">
                <p>
                   用户名 </p>
                   <p>
                    <%= f.text_field :name %>
                    </p>
                    </div>
                <div class="col-xs-10"></div>
                <div class="col-xs-10">

                  <p> 密码 </p>
                  
                   <p>
                    <%= f.text_field :password %>
                    </p>
                    </div>
                    <div class="col-xs-10"></div>
                <div class="col-xs-10">
                <p>
                   确认密码 </p>
                   <p>
                    <%= f.text_field :password_confirm %>
                    </p>
                    </div>
                    <div class="col-xs-10"></div>
                
                <div class="col-xs-10">
                <p>
                   取密钥匙</p>
                   <p>
                    <%= f.text_field :key %>
                    </p>
                    </div>
                <div class="col-xs-6">             
                <button class="btn btn-success col-xs-12" ;>注册</button>
            </div>            
        </div>
        <div class="col-xs-10"></div>
        <div class="col-xs-10"></div>
        <div class="col-xs-10"></div>
         <div class="col-xs-10">             
                <p>小提示：忘掉密码时可以凭借取密钥匙找回</p> 
            </div>
        <% end %>
    </body>

</HTML>

app/views/wzxes/_form.html.erb
<%= form_with(model: wzx, local: true) do |form| %>
  <% if wzx.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wzx.errors.count, "error") %> prohibited this wzx from being saved:</h2>

      <ul>
      <% wzx.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :wzx_name %>
  </div>

  <div class="field">
    <%= form.label :information %>
    <%= form.text_field :information, id: :wzx_information %>
  </div>

  <div class="field">
    <%= form.label :food %>
    <%= form.text_field :food, id: :wzx_food %>
  </div>

  <div class="field">
    <%= form.label :tuijian %>
    <%= form.text_field :tuijian, id: :wzx_tuijian %>
  </div>
  <div class="field">
    <%= form.label :pt %>
    <%= form.text_field :pt, id: :wzx_pt %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wzxes/edit.html.erb
<h1>Editing Wzx</h1>

<%= render 'form', wzx: @wzx %>

<%= link_to 'Show', @wzx %> |
<%= link_to 'Back', wzxes_path %>

app/views/wzxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wzxes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Information</th>
      <th>Food</th>
      <th>Tuijian</th>
      <th>Pt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wzxes.each do |wzx| %>
      <tr>
        <td><%= wzx.name %></td>
        <td><%= wzx.information %></td>
        <td><%= wzx.food %></td>
        <td><%= wzx.tuijian %></td>
        <td><%= wzx.pt %></td>
        <td><%= link_to 'Show', wzx %></td>
        <td><%= link_to 'Edit', edit_wzx_path(wzx) %></td>
        <td><%= link_to 'Destroy', wzx, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wzx', new_wzx_path %>

app/views/wzxes/new.html.erb
<h1>New Wzx</h1>

<%= render 'form', wzx: @wzx %>

<%= link_to 'Back', wzxes_path %>

app/views/wzxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wzx.name %>
</p>

<p>
  <strong>Information:</strong>
  <%= @wzx.information %>
</p>

<p>
  <strong>Food:</strong>
  <%= @wzx.food %>
</p>

<p>
  <strong>Tuijian:</strong>
  <%= @wzx.tuijian %>
</p>
<p>
  <strong>pt:</strong>
  <%= @wzx.pt %>
</p>

<%= link_to 'Edit', edit_wzx_path(@wzx) %> |
<%= link_to 'Back', wzxes_path %>